spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store_api
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    create-schemas: true
